language: go

go:
    - 1.7
    - 1.8

sudo: false

services:
  - redis-server

script:
    - go test -v -bench=.
    - go test -v -race
    - cat /tmp/broadcaster-redis-server.log
    - cat /tmp/broadcaster-redis.log
