language: go

go:
    - 1.4
    - 1.5
    - 1.6

sudo: false

services:
  - redis-server

script:
    - go test -v -bench=.
    - cat /tmp/broadcaster-redis-server.log
    - cat /tmp/broadcaster-redis.log
