language: go

go:
    - 1.7
    - 1.8
    - 1.9

sudo: false

services:
  - redis-server

script:
    - go test -v -bench=.
    - cat /tmp/broadcaster-redis-server.log
    - cat /tmp/broadcaster-redis.log
